[package]
name = "flip_coin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# We need this so we can use the rand::Rng in our code!
rand = "0.3"